spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dhple?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: devmysql
    password: Devmysql1234!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 88529025505-odd7ph3m10lk689hh6ikt04plo1b2qe3.apps.googleusercontent.com
            clientSecret: 3v-yNury7uccEVU_SQ_H2vfD
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: yl0iHPI3zDec2OotkPjJiZ9vOF3SUWvU
    tokenExpirationMsec: 864000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect